services:
  - type: web
    name: beauty-booking
    runtime: python
    plan: starter
    envVars:
      - key: PERSISTENT_DIR
        value: /persistent
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port 10000
    disk:
      name: data
      mountPath: /persistent
      sizeGB: 1